# REST API & JSON Data Extraction

## Objective

The objective of this assignment is to call a public REST API, inspect the JSON response, convert the JSON data into a structured DataFrame, and export the data into a CSV file for analysis.

## Tools Used

- Python
- Requests
- Pandas
- Jupyter Notebook
- REST API
- JSON

In [1]:
import requests
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# Public Mutual Fund API

url = "https://api.mfapi.in/mf/119551"

response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

In [3]:
# Convert the API response into JSON

data = response.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['meta', 'data', 'status'])

In [4]:
# Extract the NAV data from the JSON response

nav_data = data["data"]

print("Number of records:", len(nav_data))
print("\nFirst 5 records:")
print(nav_data[:5])

Number of records: 3289

First 5 records:
[{'date': '14-08-2026', 'nav': '107.27440'}, {'date': '13-08-2026', 'nav': '107.25640'}, {'date': '12-08-2026', 'nav': '107.20260'}, {'date': '11-08-2026', 'nav': '107.17660'}, {'date': '10-08-2026', 'nav': '107.19580'}]

In [5]:
# Convert JSON data into a Pandas DataFrame

df = pd.DataFrame(nav_data)

print("DataFrame created successfully!")
print("\nShape:", df.shape)

df.head()

DataFrame created successfully!

Shape: (3289, 2)

         date        nav
0  14-08-2026  107.27440
1  13-08-2026  107.25640
2  12-08-2026  107.20260
3  11-08-2026  107.17660
4  10-08-2026  107.19580

In [6]:
# Save the API data as a CSV file

df.to_csv("api_data.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [7]:
# Verify the exported CSV file

csv_df = pd.read_csv("api_data.csv")

print("CSV loaded successfully!")
print("Rows:", len(csv_df))
print("Columns:", list(csv_df.columns))

csv_df.head()

CSV loaded successfully!
Rows: 3289
Columns: ['date', 'nav']

         date       nav
0  14-08-2026  107.2744
1  13-08-2026  107.2564
2  12-08-2026  107.2026
3  11-08-2026  107.1766
4  10-08-2026  107.1958

## Conclusion

In this assignment, a public REST API was accessed using a Python GET request. 
The API returned mutual fund NAV information in JSON format. The JSON response 
was inspected and the required data was extracted using Python. The extracted 
data was then converted into a Pandas DataFrame and exported as a CSV file.

This exercise demonstrates the basic workflow of collecting data from a REST API 
and preparing it for further data analysis.